# SPDX-FileCopyrightText: The matrix-alertmanager-receiver Authors
# SPDX-License-Identifier: GPL-3.0-or-later

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    assignees:
      - sebhoss
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    assignees:
      - sebhoss
